name: AutomaticCheck-in
on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * 0'
    - cron: '0 18 * * 1'
    - cron: '0 19 * * 3'
    - cron: '0 20 * * 4'
    - cron: '0 21 * * 5'
    - cron: '0 22 * * 6'


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7

      - name: 'Cache pip packages'
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 'Install requirements'
        run: pip install -r ./Spider/requirements.txt

      - name: 'Working'
        run: |
          sudo cp -p ./chrome/chromedriver /usr/bin/
          chmod -R 777 /usr/bin/chromedriver
        
          python ./Spider/yuzhai.py
          python ./Spider/jueduishenyu.py
          python ./Spider/shendai.py
          python ./Spider/xingmeng.py
  
