name: Run JD Scripts

on:
  push:
    branches:
      - main  # 触发条件可以根据你的需求进行调整

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # 选择适合你的 Node.js 版本

        # Runs a single command using the runners shell
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7

      - name: 'Cache pip packages'
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

            
      - name: Navigate to the ./chrome/ directory
        run: cd ./chrome/

      - name: Install dependencies
        run: npm install ./chrome

      - name: Run jd_bean_home.js
        run: python3 ./chrome/jd.py

      # - name: Run jd_fruit.js
      #   run: node ./chrome/jd_fruit.js

      # - name: Run jd_plantBean.js
      #   run: node ./chrome/jd_plantBean.js
